ThULB/dbt

- src/main/resources/xsl/layout/dbt-layout.xsl
remove deprecated X-UA-Compatible and cleartype meta tag
> DBT-120 Do not force IE9 engine to be used wie IE11

- src/main/resources/xsl/rc/mail-events.xsl
> DBT-207 end copy details also for deleted opc entries

- src/main/resources/setup/classifications/mir_institutes.xml
> DBT-208 HSN Update

- src/main/resources/setup/classifications/mir_institutes.xml
> merge "2016.06.0.x"

- src/main/less/common/mir_metadata.less
- src/main/less/common/mir_results.less
- src/main/resources/xsl/layout/dbt-layout.xsl
- remove copy of title attribute
- fix mir state badge style
> DBT-217 fix layout issues

- src/main/resources/META-INF/resources/content/rc/slot-includes.xed
- src/main/resources/xsl/layout/dbt-layout.xsl
- src/main/resources/xsl/rc/slot.xsl
- move javascript includes to end of body
- use apply-templates instead of copy-of
> DBT-219 improve page loading speed

- src/main/resources/config/dbt/mycore.properties
also use mcore-pi configuration for URN
> DBT-199 added base configuration for DOI

- src/main/resources/xsl/layout/dbt-layout.xsl
title attribute is only filtered for <section> of MyCoReWebPage
> DBT-237 do not filter @title attribute

- src/main/resources/META-INF/resources/content/top/faq.xml
added entry about statistics and open access journals and minor changes
> DBT-241 Update FAQ

- pom.xml
- src/main/java/de/urmel_dl/dbt/viewer/DBTViewerConfigurationStrategy.java
- src/main/less/dbt/content.less
- src/main/resources/config/dbt/mycore.properties
uses default CSS layout from DBT and Bootstrap used in main app
> DBT-268 add custom MyCoRe Viewer configuration

- src/main/less/common/mir_details.less
- src/main/less/common/mir_metadata.less
MIR is using SASS now instead of less. So last time...
> DBT-269 fixed abstract and synced with MIR less files

- src/main/resources/config/dbt/mycore.properties
registering DOIs and URNs should be working again
> DBT-270 add configuration for URN and DOI

- src/main/resources/META-INF/resources/editor/editor-dbt.xed
- src/main/resources/META-INF/resources/oai/set_kulthura.xml
- src/main/resources/config/dbt/messages_de.properties
- src/main/resources/config/dbt/messages_en.properties
- src/main/resources/config/dbt/mycore.properties
- added OAI field to admin editor
- added kulthura set
> DBT-296 added Field in Admin Editor to select OAI

- src/main/resources/META-INF/resources/editor/editor-dbt.xed
- src/main/resources/config/dbt/messages_de.properties
- fixed help text
- moved oai field up
> DBT-296 fix help text

- src/main/resources/config/dbt/mycore.properties
> DBT-248 DeepGreen Integration

- src/main/resources/config/dbt/mycore.properties
should improve performance on file access
> DBT-322 use ifs2 scheme by default

- src/main/java/de/urmel_dl/dbt/rest/utils/EntityMessageBodyReader.java
- src/main/java/de/urmel_dl/dbt/rest/utils/EntityMessageBodyWriter.java
- src/main/java/de/urmel_dl/dbt/utils/EntityFactory.java
- src/main/resources/config/dbt/mycore.properties
fixes output as defined by MCR-2173
> DBT-334 fixes EntityMessageBodyReader|Writer issues

- src/main/resources/META-INF/resources/hbs/derivate-fileList.hbs
- src/main/resources/META-INF/resources/js/mir/derivate-fileList.js
copied changes from https://github.com/MyCoRe-Org/mir/pull/509
> MIR-795 upload into open directory

- src/main/resources/config/dbt/mycore.properties
https://mycore.atlassian.net/browse/DBT-342
> DBT-342 Allow HTML links in abstract

- pom.xml
- src/main/java/de/urmel_dl/dbt/rc/datamodel/Attendee.java
- src/main/java/de/urmel_dl/dbt/rc/persistency/SlotManager.java
- src/main/java/de/urmel_dl/dbt/rc/servlets/SlotListServlet.java
- src/main/java/de/urmel_dl/dbt/resolver/DebugResolver.java
- src/main/java/de/urmel_dl/dbt/servlets/DBTLoginEndpointServlet.java
- src/main/resources/META-INF/resources/authorization/accesskey-includes.xed
- src/main/resources/META-INF/resources/authorization/accesskey.xed
- src/main/resources/config/dbt/mycore.properties
- src/main/resources/xsl/accesskeys-filter.xsl
- src/test/resources/META-INF/persistence.xml
- src/test/resources/mycore.properties
* fix accesskey usage
* fix usage of MCRXMLMetadataManager
* fix usage of MCRJWTUtil
> DBT-349 prepare migration to mir LTS

- src/main/resources/META-INF/web-fragment.xml
- src/main/resources/config/dbt/mycore.properties
- added new OAI interface for discovery
> DBT-351 OAI: Neue OAI-Schnittstelle für Discovery-System

- src/main/resources/setup/data/realms.xml
> DBT-357 add FH Erfurt to Shibboleth notice

- src/main/java/de/urmel_dl/dbt/media/MediaService.java
- src/main/java/de/urmel_dl/dbt/media/commandline/MediaServiceCommands.java
- src/main/java/de/urmel_dl/dbt/media/resources/MediaServiceResource.java
- src/main/media/ts/_player/player.ts
- src/main/media/ts/_service/api.service.ts
- src/main/resources/config/dbt/mycore.properties
> Revert "DBT-358 implement subtitle support for Video Player"

- src/main/java/de/urmel_dl/dbt/enrichment/EnrichmentConfigResolver.java
- src/main/java/de/urmel_dl/dbt/enrichment/EnrichmentDebuggerServlet.java
- src/main/resources/META-INF/resources/editor/enrichmentDebugger.xed
- src/main/resources/META-INF/web-fragment.xml
- src/main/resources/config/dbt/mycore.properties
- src/main/resources/xsl/debugEnrichment.xsl
applied changes to make it run in MIR context
> DBT-359 fork enrichment debugger from ubo

- src/main/resources/setup/classifications/mir_institutes.xml
[Link to jira](https://mycore.atlassian.net/browse/DBT-379).
> DBT 379 add new organizational units to mir institutes

- src/main/resources/setup/classifications/mir_institutes.xml
> UB Weimar: Update mir_institutes.xml 

- src/main/resources/config/dbt/messages_de.properties
- src/main/resources/config/dbt/messages_en.properties
[Link to jira](https://mycore.atlassian.net/browse/DBT-382).
> DBT 382 Rename mir.date.issued from Year of publication to Published on

- src/main/resources/config/dbt/mycore.properties
[Link to jira](https://mycore.atlassian.net/browse/DBT-384).
> DBT-384 Activate pdfa validation in DBT

- src/main/resources/toc-layouts.xml
- src/main/resources/xsl/toc/custom-toc-layouts.xsl
[Link to jira](https://mycore.atlassian.net/browse/DBT-383).
Relates to [FSU040THUL-809]([FSU040THUL-809](https://servicedesk.uni-jena.de/browse/FSU040THUL-809))
> Dbt 383 add new toc option and layout names for table of contents

- src/main/resources/META-INF/resources/dbt/js/layout.js
[Link to jira](https://mycore.atlassian.net/browse/DBT-380).
> DBT-380 Keep author field expanded by default

- src/main/media/ts/_player/player.ts
- src/main/media/ts/embed.ts
To use this, set query string attribute "poster" with custom URL.
```html
<iframe width='560' height='315' frameborder='0' allowfullscreen='true' src='https://www.db-thueringen.de/rsc/media/embed/196B1E4C99F280E31A051E353DDE4BFA3C8A489B522E61B62A0A9EA7017EA3A3?objId=dbt_mods_00064988&poster=http://www.sky.de/static/img/program_guide/59542_ser_l.jpg?impolicy=bp04_teaserdata_image_16_9'></iframe>
```
> FSU040THUL allow custom video poster

- src/main/resources/META-INF/resources/config/navigation.xml
- src/main/resources/META-INF/resources/content/footer/accessibility.xml
This pull request introduces an accessibility statement to the website and updates the navigation configuration to include a link to this new section. The changes aim to improve compliance with accessibility standards and provide clear information to users about the website's accessibility efforts.
* Added a new navigation item in `navigation.xml` linking to the accessibility statement (`accessibility.xml`) with labels in German ("Barrierefreiheit") and English ("Accessibility").
* Created a new file, `accessibility.xml`, containing a detailed accessibility statement in both German and English. The statement includes compliance status, justification, creation date, contact information, and enforcement procedure.
> DBT-393 add accessiblity statement
